@isTest
public class ET_InsepctionTestResultWrapperTest {
    public static testmethod void testMethod1(){
        ET_InsepctionTestResultWrapper.Input obj = new ET_InsepctionTestResultWrapper.Input();
        ET_InsepctionTestResultWrapper.Control obj2 = new ET_InsepctionTestResultWrapper.Control();
        ET_InsepctionTestResultWrapper.Output obj3 = new ET_InsepctionTestResultWrapper.Output();
    }
}