@isTest
public class ET_MagicTestClass {
     private static testmethod void testmethodInspection(){
      
         //ET_LookupController.utilityMethod();
         //ET_Lookup_Service.utilityMethod();
         ETAbuDhabiInspectionService.utilityMethod();
         new ETAbuDhabiInspectionService.VehicleDetails();
         new ETAbuDhabiInspectionService.PlateKey();
         new ETAbuDhabiInspectionService.SetInspectionResultRequest();
         new ETAbuDhabiInspectionService.execute_pt();
         new ETAbuDhabiInspectionService.GetVehicleDetailsRequest();
         new ETAbuDhabiInspectionService.getPlateCombinationsResponse_element();
         new ETAbuDhabiInspectionService.GetVehicleTicketsRequest();
         //expt.execute(new ETAbuDhabiInspectionService.GetVehicleDetailsRequest());
         //expt.getVehicleColors(new ETAbuDhabiInspectionService.GetVehicleColorsRequest());
         ETAECustomer.utilityMethod();
         ETCustomerSoapService.utilityMethod();
         ETEmployee.utilityMethod();
         ETEmployeeService.utilityMethod();
         ETSupplier.utilityMethod();
         ETSupplierService.utilityMethod();
         ETSyncReceipts.utilityMethod();
         //ET_CreateReceipt.utilityMethod();
         ET_CreateReceiptService.utilityMethod();
         //ET_ERPVehicle.utilityMethod();
         ET_EmployeeServiceSchedule.utilityMethod();
         ET_Employee_Iterable.utilityMethod();
         ET_Fee.utilityMethod();
         ET_Fee_Service.utilityMethod();
         ET_InspectionCancellation.utilityMethod();
         ET_InspectionCancellationService.utilityMethod();
         //ET_Lookup.utilityMethod();
         //ET_SOA_Services.utilityMethod();
         OasisOpenOrgWssSecuritySecext.utilityMethod();
    }
}