@isTest
public class ETT_TyreInspectionwrapper_test {
    
    @isTest static void testMethod1(){
        
        Test.startTest();
        /*ETT_TyreInspectionCardWrapper.InspectionTechincalSkill objInspectionTechincalSkill = new ETT_TyreInspectionCardWrapper.InspectionTechincalSkill();
        objInspectionTechincalSkill.isEletornicProbinWorkingCondition = true;
        objInspectionTechincalSkill.isWearRequiredPPT = true;
        */
        ETT_TyreInspectionCardWrapper obj = new ETT_TyreInspectionCardWrapper();

        Test.stopTest();
        
        
        
        
        
        
        
    }
}