// To Bypass opportunity Trigger, whenever opportunity updated because of some action in quote...

public class opportunityTriggerByPassClass {
    Public static boolean bypassTrigger = false;
    Public opportunityTriggerByPassClass( boolean bypassTrigger){
         this(bypassTrigger);
    }
    
    Public static void utilityMethod(){
        integer i =0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}